
package com.test.webservcie;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://webservcie.test.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservcie.test.com", className = "com.test.webservcie.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservcie.test.com", className = "com.test.webservcie.SayHelloResponse")
    @Action(input = "http://webservcie.test.com/HelloService/sayHelloRequest", output = "http://webservcie.test.com/HelloService/sayHelloResponse")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello2", targetNamespace = "http://webservcie.test.com", className = "com.test.webservcie.SayHello2")
    @ResponseWrapper(localName = "sayHello2Response", targetNamespace = "http://webservcie.test.com", className = "com.test.webservcie.SayHello2Response")
    @Action(input = "http://webservcie.test.com/HelloService/sayHello2Request", output = "http://webservcie.test.com/HelloService/sayHello2Response")
    public String sayHello2(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
